name: 'SWM: Deploy to Azure'

on:
  push:
    branches: 
    - main

jobs:
  build_test:
    name: 'Build and Test'

    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        shell: bash
        #github.workspace 는 root 디렉토리를 의미함
        run: |
          echo "FUNCTION_APP_PATH=${{github.workspace}}/api" >> $GITHUB_ENV

      - name: Check environment variables
        shell: bash
        run: |
          echo $FUNCTION_APP_PATH

      - name: Checkout the repo 
        uses: actions/checkout@v2
      
      - name: Setup .NET SDK 
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'

      - name: Restore NuGet packages 
        shell: bash 
        run: |
          dotnet restore .

      - name: Build Function App 
        shell: bash
        run: |
          dotnet build . -c Release 

      - name: Test Function App 
        shell: bash 
        run: |
          dotnet test . -c Release
      
      - name: Create Function App artifact 
        shell: bash 
        run: |
          pushd "${{ env.FUNCTION_APP_PATH}}"
          dotnet publish . -c Release -o published 
          popd
